// Get all users
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlJvaG1hbiBCZW55IFJpeWFudG8iLCJ1c2VybmFtZSI6InJvaG1hbmJlbnkiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NTgwMjYxMSwiZXhwIjoxNjc1ODAyOTExfQ.LgDgATi-vwLR-FH-kCdp6oZicbuK9zaFvAQw3MM48Uo

###
// Register a new user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe",
    "username": "john",
    "email": "john@gmail.com",
    "password": "User123*",
    "password_confirmation": "User123*"
}

###
// Register a new admin
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "rohman beny riyanto",
    "username": "Rohmanbeny",
    "email": "admin@gmail.com",
    "role": "admin",
    "password": "Admin123*",
    "password_confirmation": "Admin123*"
}

###
// Register a new super admin
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Super Admin",
    "username": "superadmin",
    "email": "super@gmail.com",
    "role": "superadmin",
    "password": "SuperAdmin123*",
    "password_confirmation": "SuperAdmin123*"
}

###
// Register a new Toko
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Toko One",
    "username": "toko one",
    "email": "toko@gmail.com",
    "role": "toko",
    "password": "Toko12345*",
    "password_confirmation": "Toko12345*"
}

###
//Login a Super Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Admin123*"
}

###
// Refresh Token
GET http://localhost:5000/user/refreshtoken

###
// Logout
DELETE http://localhost:5000/users/logout

###
// Get a user
GET http://localhost:5000/users/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlJvaG1hbiBCZW55IFJpeWFudG8iLCJ1c2VybmFtZSI6InJvaG1hbmJlbnkiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NjAxNDgzMCwiZXhwIjoxNjc2MDE1MTMwfQ.t6XHyVNipIy-sYVy52fIcP6EfJjH6aTWhnYcy6wD3PA


###
// Aploud File
GET http://localhost:5000/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlJvaG1hbiBCZW55IFJpeWFudG8iLCJ1c2VybmFtZSI6InJvaG1hbmJlbnkiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NTgwMjYxMSwiZXhwIjoxNjc1ODAyOTExfQ.LgDgATi-vwLR-FH-kCdp6oZicbuK9zaFvAQw3MM48Uo